#!/usr/bin/env bash

echo "Compiling LaTeX document..."
echo

latexmk -lualatex \
        -silent \
        -f \
        -Werror \
        -file-line-error \
        -interaction=nonstopmode \
        -halt-on-error \
        -logfilewarninglist \
        main.tex 2>/dev/null | textool check main.log -p

qpdf main.pdf --linearize --replace-input

echo
echo "Cleaning up..."

mv main.log main.log.bak
latexmk -c > /dev/null 2>/dev/null
mv main.log.bak main.log
